# device settings
device: cuda  # or 'cpu'
modelname: RESC

# data settings
dataset_path: data/images  # parent directory of datasets
pre_extracted: True  # were feature preextracted with extract_features?

img_size: 256  # image size of highest scale, others are //2, //4"image width/height should be a multiple of 128"

# network hyperparameters
n_scales: 3  # number of scales at which features are extracted, img_size is the highest - others are //2, //4,...
clamp: 3  # clamping parameter
max_grad_norm: 1  # clamp gradients to this norm
n_coupling_blocks: 4  # higher = more flexible = more unstable
fc_internal: 1024  # * 4 # number of neurons in hidden layers of s-t-networks
lr_init: 0.0002  # inital learning rate
use_gamma: True

extractor: "effnetB5"  # feature dataset name (which was used in 'extract_features.py' as 'export_name')

# dataloader parameters
batch_size: 16 

# total epochs = meta_epochs * sub_epochs
# evaluation after <sub_epochs> epochs
meta_epochs: 5  # total epochs = meta_epochs * sub_epochs
sub_epochs: 60  # evaluate after this number of epochs

# output settings
verbose: True
hide_tqdm_bar: True
save_model: True
